[project]
name = "iam-policy-generator-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "boto3>=1.28.0",
    "botocore>=1.31.0",
    "gradio>=4.0.0",
    "python-dotenv>=1.0.0",
]
